name: CI Mentoria

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      API_BASE_URL: 'http://localhost:3000'
      PORT: 4000

    steps:
      - name: clone do projeto
        uses: actions/checkout@v4

      - name: instalando as dependências do projeto
        run: npm install

      - name: iniciando o servidor de mocks
        run: npm run mock-server &

      - name: iniciar o servidor de app
        run: npm run server &
